### PR TITLE
[#79] Panic instead of returning bool value

### LINKED ISSUE #79: Raise an exception instead of returning `bool` value
Currently many methods return `bool` value as a signal of success. In most of the cases just `true` value is returned. This is unneeded and we can raise an exception instead. This will also simplify response handling on caller side (either client or other contract). For example, `netmap` contract doesn't even check return values of `newEpoch` invocations of `balance` and `container` contracts. We can `panic` everywhere for consistency.

### PR DESCRIPTION
**Pull request by fyrchik**
There is a number of contracts which return only `true` value.
Also handling `FAULT` on the client is easier then also checking return
value.

Close #79 .

### CODE REVIEW

File: balance/balance_contract.go [hunk 1]
```diff
@@ -272,8 +267,6 @@ func NewEpoch(epochNum int) bool {
 			token.transfer(ctx, addr, acc.Parent, acc.Balance, true, details)
 		}
 	}
-
-	return true
 }
 
 func Mint(to interop.Hash160, amount int, txDetails []byte) bool {
```
Comment (alexvanin) [inline balance/balance_contract.go:272]: `Mint` and `Burn` methods are not the part of NEP-17. Maybe it makes sense to remove return type there as well?

Comment (fyrchik) [reply balance/balance_contract.go:272]: Yes, wiil do this.

**Review by alexvanin — APPROVED** [review]
